platform :ios, '9.0'
use_frameworks!

target 'BubbleHeader_Example' do
  pod 'BubbleHeader', :path => '../'

  target 'BubbleHeader_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots'
  end
end
